### ISSUE TITLE
Documentation for integrating with Grafana Cloud

### ISSUE THREAD

**Issue by AugustDev** [pragmaticivan/nestjs-otel#80]
Currently we can access logs, traces and metrics locally. Could you explain how to integrate it with Grafana cloud?

**Comment by pragmaticivan** [comment]
Howdy @AugustDev I will close this one because it kinda goes really out of the scope of this project.  Create a stack overflow and link this issue. This can be done via opentelemetry-js more than using this package.

One suggestion is to use a opentelemetry-collector that sends metrics and traces to Grafana cloud. Grafana has some docs once you create an account.
